version: '3.8'

services:
#  web:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - app

  user:
    image: node:18-alpine
    container_name: api-user-${DOCKER_ENV_VERSION}
    environment:
      - NODE_ENV=development
    ports:
      - "${API_USER_PORT}:3000"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: [ sh, -c, "npx nest start user --watch" ]
    networks:
      - crm-network

networks:
  crm-network:
      name: ${DOCKER_NETWORK}
      external: true

